parameters:
  table: '1P7P7LjTBJ8-7niq_C05Gpv_RfwEGpg36D8wTZ_vnrbU'
  google.client.config:
    access_type: offline
    credentials: '/var/www/bitrix24.asi/google.key.json'
    scopes:
      - !php/const Google\Service\Sheets::SPREADSHEETS
  bitrix.export.object.config:
    base_objects: 42

services:
  google.client:
    class: Google\Client
    arguments: ['%google.client.config%']
  google.sheets:
    class: Google\Service\Sheets
    arguments: ['@google.client']
  service.google.sheets:
    class: Alastor141\Google\Api\Sheets
    arguments: ['@google.sheets']
  bitrix.export.object.provider:
    class: Alastor141\Bitrix\Google\Sheets\Export\Lists\Provider
    arguments: ['%bitrix.export.object.config%']
  bitrix.export.object:
    class: Alastor141\Bitrix\Google\Sheets\Export\Lists\Export
    arguments: ['@service.google.sheets', '@bitrix.export.object.provider', '%table%']
    public: true